export const sizeVariation = {
  sm: {
    typography: 'body4',
    py: 7,
    px: 8,
    spinnerSize: 'sm',
    iconSize: 16,
    disclosureSize: 16,
    contentsSpacing: 0,
    weight: 'medium',
  },
  md: {
    typography: 'body2',
    py: 10,
    px: 10,
    spinnerSize: 'md',
    iconSize: 18,
    disclosureSize: 16,
    contentsSpacing: 0,
    weight: 'medium',
  },
  lg: {
    typography: 'body2',
    py: 13,
    px: 12,
    spinnerSize: 'md',
    iconSize: 18,
    disclosureSize: 16,
    contentsSpacing: 0,
    weight: 'bold',
  },
  xl: {
    typography: 'body1',
    py: 15,
    px: 14,
    spinnerSize: 'md',
    iconSize: 20,
    disclosureSize: 18,
    contentsSpacing: 2,
    weight: 'bold',
  },
} as const;
