import type { Colors } from '../../types';
import { palettes } from '../palettes';

export const darkModeColors: Colors = {
  primary: palettes.orange['45'],
  onPrimary: palettes.white,
  primaryContainer: palettes.orange['5'],
  onPrimaryContainer: palettes.orange['70'],
  informative: palettes.violetBlue['50'],
  onInformative: palettes.violetBlue['95'],
  informativeContainer: palettes.violetBlue['5'],
  onInformativeContainer: palettes.violetBlue['50'],
  error: palettes.red['50'],
  onError: palettes.red['95'],
  errorContainer: palettes.red['5'],
  onErrorContainer: palettes.red['50'],
  success: palettes.green['45'],
  onSuccess: palettes.green['95'],
  successContainer: palettes.green['5'],
  onSuccessContainer: palettes.green['50'],
  background: palettes.neutral['5'],
  surface1: palettes.whiteAlpha['10'],
  surface2: palettes.neutral['10'],
  surface3: palettes.black,
  surface4: palettes.neutral['30'],
  onView1: palettes.neutral['95'],
  onView2: palettes.neutral['60'],
  onView3: palettes.neutral['40'],
  outline1: palettes.whiteAlpha['15'],
  outline2: palettes.whiteAlpha['5'],
  outlinePrimary: palettes.orange['45'],
  outlineNeutral: palettes.neutral['95'],
  outlineError: palettes.red['50'],
  disable: palettes.whiteAlpha['15'],
  disableOutline: palettes.whiteAlpha['10'],
  inverseBackground: palettes.neutral['95'],
  onInverseBackground: palettes.neutral['5'],
  dim: palettes.blackAlpha['70'],
  hoverOverlay: palettes.whiteAlpha['15'],
  transparent: palettes.transparent,
  onColor: '$colors.onView1',
  white: palettes.white,
};
